##spring.application.name=hubspot
hubspot.client_id=546c6248-9948-4471-9bc7-516239afa271
hubspot.client_secret=ade85c08-cd81-4b21-a115-817c72591750
hubspot.redirect_uri=http://localhost:8080/oauth/callback
hubspot.scope=crm.objects.contacts.read crm.objects.contacts.write oauth
