##spring.application.name=hubspot
hubspot.client_id=c084bc38-e5cb-4b03-831e-5738adfbcb01
hubspot.client_secret=96205772-9dfd-43d3-964b-aaeffac20261
hubspot.redirect_uri=https://app.hubspot.com/oauth/authorize?client_id=c084bc38-e5cb-4b03-831e-5738adfbcb01&redirect_uri=http://localhost&scope=oauth
