server.port=8080
hubspot.client_id=1c7427e1-cd3d-46a3-a6fd-41416266807e
hubspot.client_secret=56987812-0bde-449c-a6cb-93b50002927a
hubspot.redirect_uri=http://localhost:8080/oauth/callback
hubspot.scope=crm.objects.contacts.read crm.objects.contacts.write
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
