##spring.application.name=hubspot
hubspot.client_id=1deaca22-5d48-466c-9611-8e7b888e91d1
hubspot.client_secret=03e7adcc-b44f-4636-9400-01690163172d
hubspot.redirect_uri=http://localhost:8080/oauth/callback
hubspot.scope=crm.objects.contacts.read crm.objects.contacts.write

